### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by JonasRosendo** [catho/teste-apps#1]
Olá,

Consegui subir o servidor nodejs, ele abre no browser, porém, o endpoint passado no arquivo README não recupera o .json
Pelo que entendi o /keys deveria trazer o seguintes dados:

`{
    auth: '1811a58a2bdceefa000c5b4bb1def4e00c8151de2e3fc1180849ce12134d763ad0416a71fd2cd59241a30a225596ecf4020498ad4b9be3b5f9220e852b86defb',
    tips: 'cbfd65590f0a9199b51fdef55e994f3b912e3d54c119fb91597a6079739e42b1e3c8ea06b4c677c857c7510757d65da5db484f30d75abcc19365521e4eb8f96a',
    suggestion: '9849ffef11e19e5255f520e97370de10d96b2fda02a7d8c6a17aaac5bc3d38544601781a64da1a9cc95ca3fd21701e4c34a7613134871eb050a464c1d34de9f8',
    survey: 'eb446b26f15f84901b24fa1ae1c439d6c42e26f0e75d5d7f4d7f17d53e9fd41bfbe0185cca58116d809327300c07360ee053ad4fb5a4567ada13f4eef38f53e8'
}`

Ao iniciar o servidor o caminho para este arquivo, através do navegador, está em http://localhost:4040/api/src/db/keys/index.js.
Testei várias combinações de rotas com Postman e nenhuma delas trouxe os dados necessários.

Ao fazer a chamada http://localhost:4040/keys recebo um retorno 404 e isso se repete em todos os endpoints mesmo passando os dados no Header da chamada.

Nunca subi um servidor nodejs, talvez eu tenha errado em alguma configuração.
Poderiam confirmar se esses dados estão realmente sendo retornados ?

Obrigado!!

**Comment by methob** [comment]
Collection pra você aí parceiro 
[catho.postman_collection.json.zip](https://github.com/catho/teste-apps/files/4907479/catho.postman_collection.json.zip)
